# Generated by Django 2.1 on 2018-08-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=25)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_content', models.CharField(max_length=100)),
            ],
        ),
    ]
