# Generated by Django 2.1 on 2018-08-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
